USE [master]
GO

/****** Object:  Database [Utilitario]    Script Date: 05/05/2024 22:59:41 ******/
CREATE DATABASE [Utilitario]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Utilitario', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.ATLAS\MSSQL\DATA\Utilitario.mdf' , SIZE = 716800KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Utilitario_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.ATLAS\MSSQL\DATA\Utilitario_log.ldf' , SIZE = 102400KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Utilitario].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Utilitario] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Utilitario] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Utilitario] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Utilitario] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Utilitario] SET ARITHABORT OFF 
GO

ALTER DATABASE [Utilitario] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Utilitario] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Utilitario] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Utilitario] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Utilitario] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Utilitario] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Utilitario] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Utilitario] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Utilitario] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Utilitario] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Utilitario] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Utilitario] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Utilitario] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Utilitario] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Utilitario] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Utilitario] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Utilitario] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Utilitario] SET RECOVERY FULL 
GO

ALTER DATABASE [Utilitario] SET  MULTI_USER 
GO

ALTER DATABASE [Utilitario] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Utilitario] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Utilitario] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Utilitario] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Utilitario] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Utilitario] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Utilitario] SET QUERY_STORE = ON
GO

ALTER DATABASE [Utilitario] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [Utilitario] SET  READ_WRITE 
GO

